export const InspectionFields = [
  {
    label: "Bus Bar",
    name: "bus_bar",
    options: ["Coated", "Barred Conductor", "Sleeve"],
    type: "select",
    device: ["Transformer", "Switch", "Fuse"],
    selectedOption: "Coated",
  },
  {
    label: "Bus Bar to DO Jumper",
    name: "busbar_do_jumper",
    options: ["Coated", "Barred Conductor", "Sleeve"],
    type: "select",
    device: ["Transformer", "Switch"],
    selectedOption: "Coated",
  },
  {
    label: "UG Cable Jumper",
    name: "ug_cable_jumper",
    options: ["Lug", "Binding", "N/A"],
    type: "select",
    device: ["Transformer"],
    selectedOption: "Lug",
  },
  {
    label: "TC Condition",
    name: "tc_condition",
    options: ["Straight", "Tilted", "Plinth", "Pole structure"],
    type: "select",
    device: ["Transformer"],
    selectedOption: "Straight",
  },
  {
    label: "Bird Guard",
    name: "bird_guard",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Transformer", "Switch"],
    selectedOption: "Yes",
  },
  {
    label: "DO to TC Jumper",
    name: "do_tc_jumper",
    options: ["Coated", "Barred Conductor", "Sleeve"],
    type: "select",
    device: ["Transformer"],
    selectedOption: "Coated",
  },
  {
    label: "Transformer HT Booting",
    name: "ht_booting",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Transformer"],
    selectedOption: "No",
  },
  {
    label: "Transformer LT Booting",
    name: "lt_booting",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Transformer"],
    selectedOption: "No",
  },
  {
    label: "Breather Installed",
    name: "breather_installed",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Transformer"],
    selectedOption: "No",
  },
  {
    label: "Silica Gel Color",
    name: "silica_gel_color",
    options: ["Blue", "Orange"],
    type: "select",
    device: ["Transformer"],
    selectedOption: "Blue",
  },
  {
    label: "Oil Leakage Visible",
    name: "oil_leakage",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Transformer"],
    selectedOption: "No",
  },
  {
    label: "Oil Level",
    name: "oil_level",
    options: ["Normal", "Low"],
    type: "select",
    device: ["Transformer"],
    selectedOption: "Normal",
  },
  {
    label: "TC Fencing",
    name: "tc_fencing",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Transformer"],
    selectedOption: "No",
  },
  {
    label: "Fuse Box (External) Condition",
    name: "fuse_box_external",
    options: ["Closed", "Open"],
    type: "radio",
    device: ["Fuse"],
    selectedOption: "Closed",
  },
  {
    label: "Fuse Box (Internal) Burnt Part",
    name: "fuse_box_internal_burn",
    options: ["Yes", "No"],
    type: "radio",
    device: ["Fuse"],
    selectedOption: "No",
  },
  {
    label: "LT Cable Connection",
    name: "lt_cable_connection",
    options: ["Lug", "Patta", "Binding"],
    type: "select",
    device: ["Transformer"],
    selectedOption: "Patta",
  },
];
